// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xiangjiandao.Infrastructure;

#nullable disable

namespace Xiangjiandao.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("longtext");

                    b.Property<string>("Xml")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.CapLock", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Instance")
                        .HasMaxLength(256)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("LastLockTime")
                        .HasColumnType("DATETIME(6)");

                    b.HasKey("Key");

                    b.ToTable("CAPLock", (string)null);
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.PublishedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Added")
                        .HasColumnType("DATETIME(6)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("Retries")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExpiresAt", "StatusName" }, "IX_ExpiresAt_StatusName");

                    b.HasIndex(new[] { "Version", "ExpiresAt", "StatusName" }, "IX_Version_ExpiresAt_StatusName");

                    b.ToTable("CAPPublishedMessage", (string)null);
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.ReceivedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Added")
                        .HasColumnType("DATETIME(6)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<string>("Group")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<int?>("Retries")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExpiresAt", "StatusName" }, "IX_ExpiresAt_StatusName")
                        .HasDatabaseName("IX_ExpiresAt_StatusName1");

                    b.HasIndex(new[] { "Version", "ExpiresAt", "StatusName" }, "IX_Version_ExpiresAt_StatusName")
                        .HasDatabaseName("IX_Version_ExpiresAt_StatusName1");

                    b.ToTable("CAPReceivedMessage", (string)null);
                });

            modelBuilder.Entity("Xiangjiandao.Domain.AggregatesModel.AdminUserAggregate.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("avatar")
                        .HasComment("用户头像");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("created_by")
                        .HasComment("创建者");

                    b.Property<sbyte>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("deleted")
                        .HasComment("是否删除");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("email")
                        .HasComment("注册邮箱");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("phone")
                        .HasComment("手机号");

                    b.Property<string>("PhoneRegion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("phone_region")
                        .HasComment("手机区号");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("role")
                        .HasComment("用户角色");

                    b.Property<string>("SecretData")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("secret_data")
                        .HasComment("密码摘要");

                    b.Property<sbyte>("Special")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("special")
                        .HasComment("是否特殊账号超级管理员");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("更新时间");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("updated_by")
                        .HasComment("更新者");

                    b.HasKey("Id");

                    b.ToTable("t_admin_user", (string)null);
                });

            modelBuilder.Entity("Xiangjiandao.Domain.AggregatesModel.AppAggregate.App", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("created_by")
                        .HasComment("创建者");

                    b.Property<sbyte>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("deleted")
                        .HasComment("是否删除");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("desc")
                        .HasComment("应用描述");

                    b.Property<string>("Link")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("link")
                        .HasComment("应用链接");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("logo")
                        .HasComment("应用图标");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("name")
                        .HasComment("应用名称");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("row_version")
                        .HasComment("并发乐观锁");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort")
                        .HasComment("应用排序");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("更新时间");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("updated_by")
                        .HasComment("更新者");

                    b.HasKey("Id");

                    b.ToTable("t_app", (string)null);
                });

            modelBuilder.Entity("Xiangjiandao.Domain.AggregatesModel.BannerAggregate.Banner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("BannerFileId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("banner_file_id")
                        .HasComment("Banner 文件 Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("created_by")
                        .HasComment("创建者");

                    b.Property<sbyte>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("deleted")
                        .HasComment("是否删除");

                    b.Property<string>("LinkAddress")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("link_address")
                        .HasComment("链接地址");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort")
                        .HasComment("排序");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("更新时间");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("updated_by")
                        .HasComment("更新者");

                    b.HasKey("Id");

                    b.ToTable("t_banner", (string)null);
                });

            modelBuilder.Entity("Xiangjiandao.Domain.AggregatesModel.GlobalConfigAggregate.GlobalConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("created_by")
                        .HasComment("创建者");

                    b.Property<sbyte>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("deleted")
                        .HasComment("是否删除");

                    b.PrimitiveCollection<string>("FoundationPublicDocument")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("foundation_public_document")
                        .HasComment("基金会公开信息文件");

                    b.Property<long>("FundScale")
                        .HasColumnType("bigint")
                        .HasColumnName("fund_scale")
                        .HasComment("基金规模");

                    b.Property<long>("IssuePointsScale")
                        .HasColumnType("bigint")
                        .HasColumnName("issue_points_scale")
                        .HasComment("发行积分规模");

                    b.Property<int>("ProposalApprovalVotes")
                        .HasColumnType("int")
                        .HasColumnName("proposal_approval_votes")
                        .HasComment("提案通过票数");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("row_version")
                        .HasComment("行版本，处理并发问题");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("更新时间");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("updated_by")
                        .HasComment("更新者");

                    b.HasKey("Id");

                    b.ToTable("t_global_config", (string)null);
                });

            modelBuilder.Entity("Xiangjiandao.Domain.AggregatesModel.InformationAggregate.Information", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AttachId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("attach_id")
                        .HasComment("附件 Id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("created_by")
                        .HasComment("创建者");

                    b.Property<sbyte>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("deleted")
                        .HasComment("是否删除");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("name")
                        .HasComment("公告名称");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("row_version")
                        .HasComment("并发乐观锁");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort")
                        .HasComment("公告排序");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("更新时间");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("updated_by")
                        .HasComment("更新者");

                    b.HasKey("Id");

                    b.ToTable("t_information", (string)null);
                });

            modelBuilder.Entity("Xiangjiandao.Domain.AggregatesModel.MedalAggregate.Medal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AttachId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("attach_id")
                        .HasComment("附件 Id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("created_by")
                        .HasComment("创建者");

                    b.Property<sbyte>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("deleted")
                        .HasComment("是否删除");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("file_id")
                        .HasComment("获得用户文件 Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("name")
                        .HasComment("勋章名称");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint")
                        .HasColumnName("quantity")
                        .HasComment("发放用户数量");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("更新时间");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("updated_by")
                        .HasComment("更新者");

                    b.HasKey("Id");

                    b.ToTable("t_medal", (string)null);
                });

            modelBuilder.Entity("Xiangjiandao.Domain.AggregatesModel.NodeAggregate.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("created_by")
                        .HasComment("创建者");

                    b.Property<sbyte>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("deleted")
                        .HasComment("是否删除");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description")
                        .HasComment("节点描述");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("logo")
                        .HasComment("节点 Logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("name")
                        .HasComment("节点名称");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort")
                        .HasComment("排序");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("更新时间");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("updated_by")
                        .HasComment("更新者");

                    b.Property<string>("UserDid")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("user_did")
                        .HasComment("节点用户 Did");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id")
                        .HasComment("节点用户 Id");

                    b.HasKey("Id");

                    b.ToTable("t_node", (string)null);
                });

            modelBuilder.Entity("Xiangjiandao.Domain.AggregatesModel.ProposalAggregate.Proposal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<long>("AgreeVotes")
                        .HasColumnType("bigint")
                        .HasColumnName("agree_votes")
                        .HasComment("同意票数");

                    b.Property<string>("AttachId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("attach_id")
                        .HasComment("附件 Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("created_by")
                        .HasComment("创建者");

                    b.Property<sbyte>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("deleted")
                        .HasComment("是否删除");

                    b.Property<DateTimeOffset>("EndAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)))
                        .HasColumnName("end_at")
                        .HasComment("投票截至时间");

                    b.Property<string>("InitiatorAvatar")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("initiator_avatar")
                        .HasComment("发起方头像");

                    b.Property<string>("InitiatorDid")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("initiator_did")
                        .HasComment("发起方 Did");

                    b.Property<string>("InitiatorDomainName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("initiator_domain_name")
                        .HasComment("发起方 DomainName");

                    b.Property<string>("InitiatorEmail")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("initiator_email")
                        .HasComment("发起方邮箱");

                    b.Property<Guid>("InitiatorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("initiator_id")
                        .HasComment("发起方名称");

                    b.Property<string>("InitiatorName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("initiator_name")
                        .HasComment("发起方名称");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("name")
                        .HasComment("提案名称");

                    b.Property<sbyte>("OnShelf")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("on_shelf")
                        .HasComment("是否上架");

                    b.Property<long>("OpposeVotes")
                        .HasColumnType("bigint")
                        .HasColumnName("oppose_votes")
                        .HasComment("反对票数");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("row_version")
                        .HasComment("行版本，处理并发问题");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("status")
                        .HasComment("提案状态");

                    b.Property<long>("TotalVotes")
                        .HasColumnType("bigint")
                        .HasColumnName("total_votes")
                        .HasComment("总投票数");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("更新时间");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("updated_by")
                        .HasComment("更新者");

                    b.HasKey("Id");

                    b.ToTable("t_proposal", (string)null);
                });

            modelBuilder.Entity("Xiangjiandao.Domain.AggregatesModel.ProposalAggregate.VoteRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("Choice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("choice")
                        .HasComment("投票选项");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("created_by")
                        .HasComment("创建者");

                    b.Property<sbyte>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("deleted")
                        .HasComment("是否删除");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("char(36)")
                        .HasColumnName("proposal_id")
                        .HasComment("提案 Id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("更新时间");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("updated_by")
                        .HasComment("更新者");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id")
                        .HasComment("投票用户 Id");

                    b.HasKey("Id");

                    b.HasIndex("ProposalId");

                    b.ToTable("t_vote_record", (string)null);
                });

            modelBuilder.Entity("Xiangjiandao.Domain.AggregatesModel.ScoreDistributeRecordAggregate.ScoreDistributeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("created_by")
                        .HasComment("创建者");

                    b.Property<sbyte>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("deleted")
                        .HasComment("是否删除");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("email")
                        .HasComment("邮箱");

                    b.Property<DateTimeOffset>("GetTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("get_time")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("获取时间");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("nick_name")
                        .HasComment("昵称");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("phone")
                        .HasComment("手机号");

                    b.Property<string>("PhoneRegion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("phone_region")
                        .HasComment("用户手机区号");

                    b.Property<long>("Score")
                        .HasColumnType("bigint")
                        .HasColumnName("score")
                        .HasComment("发放积分");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("更新时间");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("updated_by")
                        .HasComment("更新者");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id")
                        .HasComment("用户id");

                    b.HasKey("Id");

                    b.ToTable("t_point_distribute_record", (string)null);
                });

            modelBuilder.Entity("Xiangjiandao.Domain.AggregatesModel.ScoreRecordAggregate.ScoreRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("created_by")
                        .HasComment("创建者");

                    b.Property<sbyte>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("deleted")
                        .HasComment("是否删除");

                    b.Property<string>("ParticipatorDomainName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("participator_domain_name")
                        .HasComment("参与方域名");

                    b.Property<Guid>("ParticipatorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("participator_id")
                        .HasComment("积分记录的另一个参与用户 Id");

                    b.Property<string>("ParticipatorNickName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("participator_nick_name")
                        .HasComment("参与方昵称");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("reason")
                        .HasComment("获得原因");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("remark")
                        .HasComment("附言");

                    b.Property<long>("Score")
                        .HasColumnType("bigint")
                        .HasColumnName("score")
                        .HasComment("积分数量");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("type")
                        .HasComment("积分来源类型");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("更新时间");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("updated_by")
                        .HasComment("更新者");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id")
                        .HasComment("所属用户");

                    b.HasKey("Id");

                    b.ToTable("t_point_record", (string)null);
                });

            modelBuilder.Entity("Xiangjiandao.Domain.AggregatesModel.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("avatar")
                        .HasComment("用户头像");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("created_by")
                        .HasComment("创建者");

                    b.Property<sbyte>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("deleted")
                        .HasComment("是否删除");

                    b.Property<string>("Did")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("did")
                        .HasComment("DID");

                    b.Property<sbyte>("Disable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("disable")
                        .HasComment("是否禁用");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("domain_name")
                        .HasComment("完整用户名，域名");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("email")
                        .HasComment("邮箱");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("introduction")
                        .HasComment("简介");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("nick_name")
                        .HasComment("用户昵称");

                    b.Property<sbyte>("NodeUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("node_user")
                        .HasComment("是否是节点用户");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("phone")
                        .HasComment("手机号");

                    b.Property<string>("PhoneRegion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("phone_region")
                        .HasComment("手机区号");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("row_version")
                        .HasComment("行版本，处理并发问题");

                    b.Property<long>("Score")
                        .HasColumnType("bigint")
                        .HasColumnName("score")
                        .HasComment("积分");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("更新时间");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("updated_by")
                        .HasComment("更新者");

                    b.HasKey("Id");

                    b.ToTable("t_user", (string)null);
                });

            modelBuilder.Entity("Xiangjiandao.Domain.AggregatesModel.UserAggregate.UserMedal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AttachId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("attach_id")
                        .HasComment("封面 Id");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("avatar")
                        .HasComment("用户头像");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("created_by")
                        .HasComment("创建者");

                    b.Property<sbyte>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("deleted")
                        .HasComment("是否删除");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("email")
                        .HasComment("邮箱");

                    b.Property<DateTimeOffset>("GetTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)))
                        .HasColumnName("get_time")
                        .HasComment("获得时间");

                    b.Property<Guid>("MedalId")
                        .HasColumnType("char(36)")
                        .HasColumnName("medal_id")
                        .HasComment("勋章 Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("name")
                        .HasComment("勋章名称");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("nick_name")
                        .HasComment("用户昵称");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("phone")
                        .HasComment("用户手机号");

                    b.Property<string>("PhoneRegion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("phone_region")
                        .HasComment("用户手机区号");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("current_timestamp")
                        .HasComment("更新时间");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar")
                        .HasDefaultValue("")
                        .HasColumnName("updated_by")
                        .HasComment("更新者");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id")
                        .HasComment("用户 Id");

                    b.HasKey("Id");

                    b.ToTable("t_user_medal", (string)null);
                });

            modelBuilder.Entity("Xiangjiandao.Domain.AggregatesModel.ProposalAggregate.VoteRecord", b =>
                {
                    b.HasOne("Xiangjiandao.Domain.AggregatesModel.ProposalAggregate.Proposal", "Proposal")
                        .WithMany("Votes")
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("Xiangjiandao.Domain.AggregatesModel.ProposalAggregate.Proposal", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
